/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CategoriaController;
import Controller.CategoriaProdutoController;
import Model.Categoria;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paulo
 */
public class SelecionarCategorias extends javax.swing.JFrame {

    int produtoID;
    /**
     * Creates new form SelecionarCategorias
     */
    public SelecionarCategorias() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    SelecionarCategorias(int codigoProduto, String nome) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        txtCodigoCadProduto.setText(nome);
        
        produtoID = codigoProduto;
        //Peço ao controller resgatar os clientes do banco de dados
        ArrayList<Categoria> linhasCategoria = CategoriaController.PesquisarTodos();
        ArrayList<Categoria> linhasCategoriaProduto = CategoriaProdutoController.Pesquisar(codigoProduto);
        
        DefaultTableModel tmProdutos = new DefaultTableModel(){
            @Override
            public Class getColumnClass(int column) {
                switch (column) {
                    case 0:
                        return Boolean.class;
                    case 1:
                        return String.class;
                    case 2:
                        return String.class;
                }
                return null;
            }
        };
        tmProdutos.addColumn("Selecione");
        tmProdutos.addColumn("ID");
        tmProdutos.addColumn("Categoria");
        tblProdutoCategoria.setModel(tmProdutos);
        
        for(Categoria c:linhasCategoria)
        {
            boolean selected = false;
            if(linhasCategoriaProduto != null){
                for(Categoria cat: linhasCategoriaProduto){
                    if(cat.getId() == c.getId()) selected = true;
                }
            }
            tmProdutos.addRow(new Object[]{selected,c.getId(),c.getNome()});
            }
        }
 


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoriaDAO1 = new DAO.CategoriaDAO();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutoCategoria = new javax.swing.JTable();
        btnSalvarProduto1 = new javax.swing.JButton();
        lblCodigoCadProduto = new javax.swing.JLabel();
        txtCodigoCadProduto = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblProdutoCategoria.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        tblProdutoCategoria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblProdutoCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Selecione", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProdutoCategoria.setFillsViewportHeight(true);
        tblProdutoCategoria.setName(""); // NOI18N
        tblProdutoCategoria.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblProdutoCategoria);
        if (tblProdutoCategoria.getColumnModel().getColumnCount() > 0) {
            tblProdutoCategoria.getColumnModel().getColumn(0).setMinWidth(80);
        }
        tblProdutoCategoria.getAccessibleContext().setAccessibleParent(tblProdutoCategoria);

        btnSalvarProduto1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnSalvarProduto1.setText("Salvar");
        btnSalvarProduto1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSalvarProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarProduto1ActionPerformed(evt);
            }
        });

        lblCodigoCadProduto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCodigoCadProduto.setText("Produto:");

        txtCodigoCadProduto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCodigoCadProduto.setEnabled(false);
        txtCodigoCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoCadProdutoActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSalvarProduto1)
                        .addGap(466, 466, 466)
                        .addComponent(btnCancelar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCodigoCadProduto)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigoCadProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoCadProduto)
                    .addComponent(txtCodigoCadProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarProduto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarProduto1ActionPerformed
        ArrayList<Categoria> cat = new ArrayList<>();
        for(int i=0; i < tblProdutoCategoria.getRowCount(); i++){
            if(true == (boolean) tblProdutoCategoria.getValueAt(i,0)){
                cat.add(new Categoria(Integer.parseInt(tblProdutoCategoria.getValueAt(i,1).toString()),tblProdutoCategoria.getValueAt(i,2).toString()));
            }
        }
        if(!CategoriaProdutoController.Salvar(cat,produtoID)){
            JOptionPane.showMessageDialog(null,"Falha ao cadastrar produto!");
            return;
        }
        
        AtualizarExcluirProduto form2 = new AtualizarExcluirProduto();  
        form2.setVisible(true);  
        dispose();
    }//GEN-LAST:event_btnSalvarProduto1ActionPerformed

    private void txtCodigoCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoCadProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoCadProdutoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        AtualizarExcluirProduto form2 = new AtualizarExcluirProduto();  
        form2.setVisible(true);  
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelecionarCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelecionarCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelecionarCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelecionarCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelecionarCategorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvarProduto1;
    private DAO.CategoriaDAO categoriaDAO1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigoCadProduto;
    private javax.swing.JTable tblProdutoCategoria;
    private javax.swing.JTextField txtCodigoCadProduto;
    // End of variables declaration//GEN-END:variables
}
